resolver: lts-17.2
packages:
- .
extra-deps:
# TODO use version from stackage once this fix is relased https://github.com/reanimate/reanimate/commit/f4878053b1433487d6a2aeebfebd8e171732a155
- git: https://github.com/reanimate/reanimate.git
  commit: f4878053b1433487d6a2aeebfebd8e171732a155